### ISSUE TITLE
Keine Verbindung zur Wallbox und zum Portal

### ISSUE THREAD

**Issue by MyGitIT** [rxhan/RSCPGui#19]
Hallo,
in der aktuellen Version vom 19.04.21 wird die Wallbox (Easy Connect) nicht angezeigt und eine Verbindung zum Portal ist nicht möglich.
![Bildschirmfoto vom 2021-04-19 22-18-20](https://user-images.githubusercontent.com/79418392/115298233-80ced080-a15d-11eb-9447-b7148d9243f5.png)

**Comment by j64bit** [comment]
Habe das gleiche Problem. Der Einstellungen\Verbindungstest meldet: Keine Verbindung möglich.

[Passwort und User habe ich x-mal getestet. Funktionieren bei der Webseite, aber nicht hier]

Im Log stehen dann etliche Meldung wie:
```
2021-04-25 12:17:49,134 - e3dcwebgui - ERROR - ConID: 1619345868.81 - Fehler beim Verarbeiten der Daten : 9 is not a valid RSCPTag
Traceback (most recent call last):
  File "e3dcwebgui.py", line 279, in on_message
  File "e3dc\_rscp_utils.py", line 108, in decode_server_data
  File "e3dc\_rscp_utils.py", line 124, in decode_data
  File "e3dc\_rscp_utils.py", line 129, in decode_data
  File "C:\Users\Johannes\AppData\Local\Programs\Python\Python38\lib\enum.py", line 315, in __call__
  File "C:\Users\Johannes\AppData\Local\Programs\Python\Python38\lib\enum.py", line 617, in __new__
ValueError: 9 is not a valid RSCPTag
```

**Comment by j64bit** [comment]
Upload von ano. DEBUG Daten liefert auch eine Fehlermeldung bei der Überlieferung der Daten (200).

**Comment by j64bit** [comment]
OK, Problem gelöst: ich habe am Gerät beide RSCP Passwörter gesetzt und in rscpgui eingegeben.
Jetzt funktioniert die Verbindung wieder tadellos.

Hauptmenü->Personalisieren->Benutzerprofil und Pfeil nach unten (wenn ich mich richtig erinnere).
