### ISSUE TITLE
Daten aus S10X werden nicht angezeigt

### ISSUE THREAD

**Issue by ms220112** [rxhan/RSCPGui#31]
Hallo,

ich konnte mich zwar mit dem Programm an unsere neue S10X anbinden, es werden Daten wie Seriennummern der Module angezeigt, die Leistungswerte sind aber alle leer.
Muss ich noch irgend etwas machen oder funktioniert das Programm mit einer S10X nicht?

**Comment by ms220112** [comment]
Hallo,
moch ein Hinweis, im Log steht folgende Fehlermeldung:
2022-11-23 10:01:15,764 - rscpguiframe - ERROR - Fehler beim Abruf der EMS-Daten
Traceback (most recent call last):
  File "rscpguiframe.py", line 372, in updateTab
  File "rscpguiframe.py", line 776, in fill_ems_basis
  File "e3dc\rscp_helper.py", line 543, in get_data
  File "e3dc\e3dc.py", line 53, in send_requests
  File "e3dc\e3dc.py", line 95, in send_request
e3dc._rscp_exceptions.RSCPCommunicationError: ('Error type returned: 6', <Logger e3dc.e3dc (ERROR)>, 6)
2022-11-23 10:01:19,268 - rscpguiframe - ERROR - Fehler beim Abruf der EMS-Daten
Traceback (most recent call last):
  File "rscpguiframe.py", line 370, in updateTab
  File "rscpguiframe.py", line 885, in fill_ems_power
  File "e3dc\_rscp_dto.py", line 105, in __getitem__
AttributeError
2022-11-23 10:01:24,117 - rscpguiframe - ERROR - Fehler beim Parsen der Modul-Software-Versionen (libTelnetConsole / 2.0.10 [Jan 18 2022 15:48:42] (SVN: 57445)): list index out of range
2022-11-23 10:29:00,686 - rscpguiframe - ERROR - Fehler beim Parsen der Modul-Software-Versionen (libTelnetConsole / 2.0.10 [Jan 18 2022 15:48:42] (SVN: 57445)): list index out of range

**Comment by christoph-spielmann** [comment]
Bei mir treten nach einem Firmware-Update des Wechselrichters die gleichen Fehler auf. Habe einen S10 E PRO.

**Comment by rxhan** [comment]
Ich kann das Problem leider mangels Gerät nicht nachstellen. Wenn ihr mir die Daten über "anonymisierte Debugdaten an Entwickler senden" zukommen lasst, kann ich mal nachsehen wo es hackt.

**Comment by ms220112** [comment]
Hallo,

 

ich habe die Daten gerade übermittelt.

Speicherpfad: https://pv.pincrushers.de/rscpgui/1677236744_3a1b4d92a931fe312045b42aab023ef6.json

 

Mit freundlichen Grüßen

 

Michael Sulz

 

Von: rxhan ***@***.***> 
Gesendet: Mittwoch, 22. Februar 2023 01:19
An: rxhan/RSCPGui ***@***.***>
Cc: ms220112 ***@***.***>; Author ***@***.***>
Betreff: Re: [rxhan/RSCPGui] Daten aus S10X werden nicht angezeigt (Issue #31)

 

Ich kann das Problem leider mangels Gerät nicht nachstellen. Wenn ihr mir die Daten über "anonymisierte Debugdaten an Entwickler senden" zukommen lasst, kann ich mal nachsehen wo es hackt.

**Comment by ms220112** [comment]
Hallo,
mit dem neuen Release werden bis auf die Wallbox alle relevanten Daten angezeigt.
Aus meiner Sicht ist dieser Issue damit erledigt.
