### ISSUE TITLE
Kompatibel mit S10 Mini?

### ISSUE THREAD

**Issue by HarrysLapTimer** [rxhan/RSCPGui#32]
Ich hatte das schon auf dem Photovoltaik-Forum gefragt, da aber keine Antwort erhalten...

Ich starte RSCPGui per `python3 main.py` auf macOS. Das klappt gut und das GUI erscheint.
Ich gebe Web-Nutzername und Web-Password ein, außerdem noch die Seriennummer.
RSCP Password ist nicht gesetzt, Zugriff in Web-Variante.
Der S10 ist ein Mini und steht ca. 1000km entfernt - also kein lokaler Zugriff möglich.
Beim Drücken auf "Verbindungstest" erscheint "Error / Verbindung konnte nicht aufgebaut werden".

Im Terminal erscheint
```
Exception ignored in: <function E3DCWeb.__del__ at 0x7fe97925caf0>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 310, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function E3DCWeb.__del__ at 0x7fe97925caf0>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 310, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function E3DCWeb.__del__ at 0x7fe97925caf0>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 310, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'

```

In rscpgui.log sehe ich: 
```
2023-01-16 17:40:10,436 - e3dcwebgui - ERROR - ConID: 1673887210.41 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-01-16 17:40:10,520 - rscpguimain - ERROR - Fehler beim Aufbau der Web Verbindung
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 323, in gui
    result = test_connection(testgui)
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 253, in test_connection
    return testgui.get_data(requests, True)
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 59, in get_data
    raise Exception('WebGui Verbindungsaufbau fehlgeschlagen, Timeout: ' + error)
Exception: WebGui Verbindungsaufbau fehlgeschlagen, Timeout: Connection closed
2023-01-16 17:40:10,524 - rscpguimain - ERROR - Es konnte keine Verbindungsart ermittelt werden
2023-01-16 17:40:10,542 - e3dcwebgui - ERROR - ConID: 1673887210.52 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-01-16 17:41:30,246 - e3dcwebgui - ERROR - ConID: 1673887290.22 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-01-16 17:41:30,327 - rscpguiframe - ERROR - Verbindungstest nicht erfolgreich
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguiframe.py", line 1567, in bTestClick
    raise Exception('Keine Verbindungsart möglich')
Exception: Keine Verbindungsart möglich
2023-01-16 17:41:30,351 - e3dcwebgui - ERROR - ConID: 1673887290.33 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-01-16 17:48:58,147 - e3dcwebgui - ERROR - ConID: 1673887738.12 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-01-16 17:48:58,228 - rscpguiframe - ERROR - Verbindungstest nicht erfolgreich
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguiframe.py", line 1567, in bTestClick
    raise Exception('Keine Verbindungsart möglich')
Exception: Keine Verbindungsart möglich
2023-01-16 17:48:58,252 - e3dcwebgui - ERROR - ConID: 1673887738.23 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
```

**Comment by rxhan** [comment]
Die Meldung "SSL: CERTIFICATE_VERIFY_FAILED" deutet darauf hin, dass der Mac das Zertifikat von E3DC nicht akzeptiert bzw. der Zertifkatsspeicher nicht richtig angesteuert wird. Da ich keinen MAC habe kann ich das nicht überprüfen bzw. kenne auch nicht die Funktionsweise der Zertifikatsspeicher dort. Dürfte aber ähnlich wie bei Linux arbeiten, wobei zumindest ein Raspberry definitiv funktioniert.

Mit etwas programmierkentnisse sollte die SSL-Verifizierung auch deaktivierbar sein, in e3dcwebgui.py müsste websocket.WebSocketApp angepasst werden.

Vielleicht ist das hier ein Weg: https://github.com/aaugustin/websockets/issues/480

Schonmal mit Windows oder Linux getestet?

**Comment by HarrysLapTimer** [comment]
Ich habe das auch mit dem Binary für Windows getestet (auf einem Mini-PC), da bekomme ich das gleiche Ergebnis. Deshalb hatte ich nach Kompatibilität für den Mini gefragt. Username/Password habe ich gefühlt 100 mal überprüft und geht auch im Portal.

Ich probiere das mit der SSL Deaktivierung - mir kommt das aber komisch vor. Ich habe parallel eine E3DC Integration mit der Library aus [fsantini](https://github.com/fsantini)/[python-e3dc](https://github.com/fsantini/python-e3dc) am Laufen, die wird ja auch SSL verwenden. Zugang auch per Web.

**Comment by rxhan** [comment]
Das ist in der tat merkwürdig, zumal RSCPGui auf der Library von fsantini aufbaut und auch die selbe Websocket-Lib verwendet (mit den selben Parametern) Vielleicht liegt es auch doch an etwas anderem.
Du könntest mit -v DEBUG die Logausgabe erweitern. Dann sollte der Verbindungsaufbau genauer protokolliert werden.

**Aber Vorsicht: Bei der Option werden auch Übertragungsdaten protokolliert also auch die Zugangsdaten, also bitte nicht die gesamte Log anhängen.**

**Comment by rxhan** [comment]
E3DC hat scheinbar die WebSocket-Kommunikation angepasst. Das habe ich im Master Branch berücksichtigt, ggfls. löst das dein Problem.
https://github.com/rxhan/RSCPGui/commit/ba05f96d2c3c3a370e593c297d966e7c4d60a8ae

**Comment by HarrysLapTimer** [comment]
Danke fürs Kümmern. Ich habe die neue Version gezogen, python3 main.py eingegeben. Email und Password waren noch gespeichert (sonst hatte ich nichts eingegeben). Druck auf Verbindungstest resultiert in Fehlermeldung wie gehabt und Ausgabe im Log:

```
Harrys-MacBook-Pro-2:RSCPGui Harald$ python3 main.py
Exception ignored in: <function E3DCWeb.__del__ at 0x7fdc70793b80>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 320, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function E3DCWeb.__del__ at 0x7fdc70793b80>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 320, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'

```

**Comment by rxhan** [comment]
Das RSCP-Passwort musst du in den Einstellungen mit eingeben, sonst geht die Websocket-Verbindung nicht. Das habe ich aus deinem ersten Post überlesen.

**Comment by HarrysLapTimer** [comment]
Aha, das ist mir neu. Ich hatte mich an [python-e3dc](https://github.com/fsantini/python-e3dc) orientiert, da ist für den Zugriff per Web kein RSCP Passwort notwendig. Und das stimmt auch, ich greife über diese Library erfolgreich zu.

Dann muss ich mal schauen wie ich meinen Vater durch das WebUI leite um das zu finden. 8-)

**Comment by rxhan** [comment]
Ich war bislang immer der Meinung, dass die RSCP-Zugangsdaten bei der Websocket-Verbindung mitgesendet werden müssen. Ich teste heute Abend mal, ob es nicht auch ohne geht. Wenn die andere Lib das hinbekommt, sollte es ja machbar sein.

**Comment by HarrysLapTimer** [comment]
Super, Danke.

**Comment by rxhan** [comment]
Ich habs gerade überprüft, ich kann eine Websocket-Verbindung ohne RSCP-Passwort mit der aktuellen Version (Master-Branch) herstellen. Weicht deine Umgebung ggfls. mit der von der python-e3dc Lib ab? Andere Python-Version? Der SSL-Fehler macht mich auch stutzig, der dürfte nur kommen, wenn das Zertifikat nicht gültig ist.

Ich hab mal einen Branch erstellt, in dem die SSL-Verifikation deaktiviert werden kann. Vielleicht kannst du das damit testen:

https://github.com/rxhan/RSCPGui/tree/verify_ssl

In der Config unter [Login] kann mit der Version ein Schlüssel "verify_ssl = False" (default ist True) gesetzt werden. Dann wird das Zertifikat der Websocket-Verbindung nicht mehr überprüft.

**Comment by HarrysLapTimer** [comment]
Ich habe den verify_ssl Branch gezogen und die verify_ssl=False in die Konfiguration übernommen. Die Konfiguration wird auch gelesen (Nutzername, Password, Seriennummer werden übernommen).

Funktionieren tut es aber immer noch nicht, unverändertes Verhalten. Auf der Kommandozeile weiterhin
```
Harrys-MacBook-Pro-2:RSCPGui Harald$ python3 main.py
Exception ignored in: <function E3DCWeb.__del__ at 0x7fc01837fb80>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 325, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function E3DCWeb.__del__ at 0x7fc01837fb80>
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 325, in __del__
    self.ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

Im Log steht:
```
2023-02-24 14:36:44,577 - e3dcwebgui - ERROR - ConID: 1677245804.56 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-02-24 14:36:44,660 - rscpguimain - ERROR - Fehler beim Aufbau der Web Verbindung
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 325, in gui
    result = test_connection(testgui)
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 255, in test_connection
    return testgui.get_data(requests, True)
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 59, in get_data
    raise Exception('WebGui Verbindungsaufbau fehlgeschlagen, Timeout: ' + error)
Exception: WebGui Verbindungsaufbau fehlgeschlagen, Timeout: Connection closed
2023-02-24 14:36:44,660 - rscpguimain - ERROR - Es konnte keine Verbindungsart ermittelt werden
2023-02-24 14:36:44,662 - rscpguiframe - ERROR - Verbindungstest nicht erfolgreich
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguiframe.py", line 1594, in bTestClick
    raise Exception('Keine Verbindungsart möglich')
Exception: Keine Verbindungsart möglich
2023-02-24 14:36:44,683 - e3dcwebgui - ERROR - ConID: 1677245804.66 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-02-24 14:37:52,301 - e3dcwebgui - ERROR - ConID: 1677245872.28 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-02-24 14:37:52,383 - rscpguimain - ERROR - Fehler beim Aufbau der Web Verbindung
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 325, in gui
    result = test_connection(testgui)
  File "/Users/Harald/Projekte/RSCPGui/rscpguimain.py", line 255, in test_connection
    return testgui.get_data(requests, True)
  File "/Users/Harald/Projekte/RSCPGui/e3dcwebgui.py", line 59, in get_data
    raise Exception('WebGui Verbindungsaufbau fehlgeschlagen, Timeout: ' + error)
Exception: WebGui Verbindungsaufbau fehlgeschlagen, Timeout: Connection closed
2023-02-24 14:37:52,384 - rscpguimain - ERROR - Es konnte keine Verbindungsart ermittelt werden
2023-02-24 14:37:52,405 - e3dcwebgui - ERROR - ConID: 1677245872.38 - Verbindungsfehler [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
2023-02-24 14:37:52,486 - rscpguiframe - ERROR - Fehler bei der Datenübertragung an Server https://pv.pincrushers.de/rscpgui
Traceback (most recent call last):
  File "/Users/Harald/Projekte/RSCPGui/rscpguiframe.py", line 1831, in sendToServer
    raise Exception('Fehler bei Datenübermittlung' + res['error'])
Exception: Fehler bei DatenübermittlungDatenüberprüfung schlug fehl
```

Weiterhin SSL Fehler - verstehe ich nicht.

**Comment by HarrysLapTimer** [comment]
Warte mal mit weiterer Arbeit. Ich denke es gibt in der Tat ein Problem mit meiner Python3 Umgebung... Melde mich wieder.
