### ISSUE TITLE
Wallbox wird nicht mehr erkannt

### ISSUE THREAD

**Issue by ms220112** [rxhan/RSCPGui#46]
Hallo,
ich habe das neue Release von der GUI und eine s10x mit dem Softwarerelase H20_2023_044.

Mit der neuen Version wird die angeschlossene Walbox von e3dc Version 2 nicht mehr erkannt. Im vorhergehenden Release aus September 2023 wird die Wallbox noch erkannt.

**Comment by Spliff58** [comment]
S10-2023-044 zeigt auch keine Werte aus der e3dc Wallbox

**Comment by ms220112** [comment]
Hier noch das dazugehörige log:
2024-03-02 11:37:51,801 - rscpguiframe - ERROR - Fehler beim Abruf der WB-Daten
Traceback (most recent call last):
  File "rscpguiframe.py", line 411, in updateTab
  File "rscpguiframe.py", line 1599, in fill_wb
  File "rscpguimain.py", line 1196, in fill_wb
  File "rscpguimain.py", line 1187, in _fill_wb
  File "e3dcwebgui.py", line 62, in get_data
  File "e3dcwebgui.py", line 253, in getRSCPToServer
  File "e3dc\_rscp_utils.py", line 58, in encode_data
  File "e3dc\_rscp_utils.py", line 77, in encode_data
UnboundLocalError: local variable 'res' referenced before assignment
2024-03-02 11:37:55,573 - e3dcwebgui - ERROR - ConID: 1709375868.35 - Verbindungsfehler E3DCWeb.start_ws.<locals>.on_close() takes 1 positional argument but 3 were given

**Comment by Softgrider** [comment]
Moin, gibt es hier eine Aktion. Meine MulitConnect II mit RFID wurde noch nie erkannt.
Leider kann man ja keine alten Versionen mehr testen.
