### ISSUE TITLE
AssertionError/ValueError

### ISSUE THREAD

**Issue by christof1977** [rxhan/RSCPGui#48]
Hallo,

ich nutze Dein tolles Programm im Konsolenmodus (Aufruf python3 ./main.py -c -e), vorher konfiguriert mit Hilfe der GUI. Die Daten werden als MQTT-Messages exportiert, das funktioniert auch soweit. Allerdings hab ich in meinen Logfiles ständig die angehängten Fehlermeldungen. Dabei handelt es sich um alle möglichen Parameter, bei denen es fehlschlägt. Ich komme leider nicht dahinter, wie man das beheben kann.

```
Mär 15 22:09:00 dose python3[3423369]: 2024-03-15 22:09:00,899 - rscpguimain - ERROR - Fehler beim Abruf von PVI
Mär 15 22:09:00 dose python3[3423369]: Traceback (most recent call last):
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/rscpguimain.py", line 1020, in getUploadDataFromPath
Mär 15 22:09:00 dose python3[3423369]:     pvi_data[index] = self.gui.get_data(self.gui.getPVIData(pvi_index=index), True).asDict()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/rscp_helper.py", line 587, in get_data
Mär 15 22:09:00 dose python3[3423369]:     responses = self.e3dc.send_requests(requests, waittime=waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 69, in send_requests
Mär 15 22:09:00 dose python3[3423369]:     response =  self.send_request(prepared_data, True, waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 114, in send_request
Mär 15 22:09:00 dose python3[3423369]:     response = self._receive()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 155, in _receive
Mär 15 22:09:00 dose python3[3423369]:     decrypted_data = self.encrypt_decrypt.decrypt(data)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/_rscp_encrypt_decrypt.py", line 56, in decrypt
Mär 15 22:09:00 dose python3[3423369]:     decrypt = cbc.decrypt(encrypted_data)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/env/lib/python3.9/site-packages/py3rijndael/rijndael.py", line 217, in decrypt
Mär 15 22:09:00 dose python3[3423369]:     assert len(cipher) % self.block_size == 0
Mär 15 22:09:00 dose python3[3423369]: AssertionError
Mär 15 22:09:00 dose python3[3423369]: 2024-03-15 22:09:00,926 - rscpguimain - ERROR - Fehler beim Abruf von PVI
Mär 15 22:09:00 dose python3[3423369]: Traceback (most recent call last):
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/rscpguimain.py", line 1020, in getUploadDataFromPath
Mär 15 22:09:00 dose python3[3423369]:     pvi_data[index] = self.gui.get_data(self.gui.getPVIData(pvi_index=index), True).asDict()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/rscp_helper.py", line 472, in getPVIData
Mär 15 22:09:00 dose python3[3423369]:     data = self.get_data([r], True)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/rscp_helper.py", line 587, in get_data
Mär 15 22:09:00 dose python3[3423369]:     responses = self.e3dc.send_requests(requests, waittime=waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 69, in send_requests
Mär 15 22:09:00 dose python3[3423369]:     response =  self.send_request(prepared_data, True, waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 114, in send_request
Mär 15 22:09:00 dose python3[3423369]:     response = self._receive()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 155, in _receive
Mär 15 22:09:00 dose python3[3423369]:     decrypted_data = self.encrypt_decrypt.decrypt(data)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/_rscp_encrypt_decrypt.py", line 56, in decrypt
Mär 15 22:09:00 dose python3[3423369]:     decrypt = cbc.decrypt(encrypted_data)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/env/lib/python3.9/site-packages/py3rijndael/rijndael.py", line 217, in decrypt
Mär 15 22:09:00 dose python3[3423369]:     assert len(cipher) % self.block_size == 0
Mär 15 22:09:00 dose python3[3423369]: AssertionError
Mär 15 22:09:00 dose python3[3423369]: 2024-03-15 22:09:00,954 - rscpguimain - ERROR - Fehler beim Abruf von PVI
Mär 15 22:09:00 dose python3[3423369]: Traceback (most recent call last):
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/rscpguimain.py", line 1020, in getUploadDataFromPath
Mär 15 22:09:00 dose python3[3423369]:     pvi_data[index] = self.gui.get_data(self.gui.getPVIData(pvi_index=index), True).asDict()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/rscp_helper.py", line 472, in getPVIData
Mär 15 22:09:00 dose python3[3423369]:     data = self.get_data([r], True)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/rscp_helper.py", line 587, in get_data
Mär 15 22:09:00 dose python3[3423369]:     responses = self.e3dc.send_requests(requests, waittime=waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 69, in send_requests
Mär 15 22:09:00 dose python3[3423369]:     response =  self.send_request(prepared_data, True, waittime)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 114, in send_request
Mär 15 22:09:00 dose python3[3423369]:     response = self._receive()
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/e3dc.py", line 166, in _receive
Mär 15 22:09:00 dose python3[3423369]:     rscp_dto = self.rscp_utils.decode_data(decrypted_data)
Mär 15 22:09:00 dose python3[3423369]:   File "/home/heizung/RSCPGui/e3dc/_rscp_utils.py", line 137, in decode_data
Mär 15 22:09:00 dose python3[3423369]:     data_tag = RSCPTag(data_tag_hex)
Mär 15 22:09:00 dose python3[3423369]:   File "/usr/lib/python3.9/enum.py", line 360, in __call__
Mär 15 22:09:00 dose python3[3423369]:     return cls.__new__(cls, value)
Mär 15 22:09:00 dose python3[3423369]:   File "/usr/lib/python3.9/enum.py", line 677, in __new__
Mär 15 22:09:00 dose python3[3423369]:     raise ve_exc
Mär 15 22:09:00 dose python3[3423369]: ValueError: 558790345 is not a valid RSCPTag
```

**Comment by christof1977** [comment]
Ich sehe gerade, dass dieses Issue ein Dulikat von #42 sein könnte.
